languageCode = "en-us"
title = "BitwiseOR"
baseurl = "/"

paginate = "10" # Number of posts per page
theme = "mainroad"
googleAnalytics = "UA-41468102-1" # Enable Google Analytics by entering your tracking id

[Author]
    name = "Jay Lindquist"
    bio = "Developer and wonderer"
    avatar = "images/avatar.jpg"


[Params]
    subtitle = "Like || but with bits" # Subtitle of your site
    description = "" # Description of your site
    opengraph = true
    leftsidebar = true # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget